export const CATEGORIES = [
  'Arte y coleccionables',
  'Bebés y niños',
  'Belleza y cuidado personal',
  'Calzado',
  'Deportes',
  'Electrodomésticos',
  'Herramientas',
  'Hogar',
  'Indumentaria',
  'Instrumentos musicales',
  'Jardín y exterior',
  'Juguetes',
  'Libros y música',
  'Mascotas',
  'Muebles',
  'Tecnología',
  'Vehículos y accesorios',
  'Otros',
];

export const COUNTRIES = ['Uruguay', 'Argentina', 'Brasil', 'Chile', 'Paraguay'];

// Uruguay's 19 departamentos, used as the "Ciudad" options in Publicar.
export const CITIES = [
  'Artigas',
  'Canelones',
  'Cerro Largo',
  'Colonia',
  'Durazno',
  'Flores',
  'Florida',
  'Lavalleja',
  'Maldonado',
  'Montevideo',
  'Paysandú',
  'Río Negro',
  'Rivera',
  'Rocha',
  'Salto',
  'San José',
  'Soriano',
  'Tacuarembó',
  'Treinta y Tres',
];

// Montevideo is the only city with a dedicated "Barrio" selector — the
// other departamentos don't map onto this same neighborhood structure.
export const MONTEVIDEO_NEIGHBORHOODS = [
  'Aguada',
  'Aires Puros',
  'Atahualpa',
  'Bañados de Carrasco',
  'Barrio Sur',
  'Belvedere',
  'Bolívar',
  'Brazo Oriental',
  'Buceo',
  'Capurro',
  'Carrasco',
  'Carrasco Norte',
  'Casabó',
  'Casavalle',
  'Cerrito',
  'Cerro',
  'Ciudad Vieja',
  'Colón',
  'Colón Sudeste',
  'Conciliación',
  'Cordón',
  'Flor de Maroñas',
  'Ituzaingó',
  'Jacinto Vera',
  'La Blanqueada',
  'La Comercial',
  'La Figurita',
  'La Teja',
  'Larrañaga',
  'Las Acacias',
  'Las Canteras',
  'Malvín',
  'Malvín Norte',
  'Manga',
  'Maroñas',
  'Mercado Modelo',
  'Nuevo París',
  'Palermo',
  'Parque Batlle',
  'Parque Rodó',
  'Paso de la Arena',
  'Paso de las Duranas',
  'Paso Molino',
  'Peñarol',
  'Piedras Blancas',
  'Pocitos',
  'Pocitos Nuevo',
  'Prado',
  'Punta Carretas',
  'Punta Gorda',
  'Reducto',
  'Sayago',
  'Tres Cruces',
  'Tres Ombúes',
  'Unión',
  'Villa del Cerro',
  'Villa Española',
  'Villa García',
];

export const CURRENCIES = [
  { code: 'UYU', label: 'Pesos uruguayos ($)', symbol: '$' },
  { code: 'USD', label: 'Dólares estadounidenses (US$)', symbol: 'US$' },
];
